{% set name = "sphinx-argparse" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ddf6000f5dbf46a737720a020442dbd355293c92d130ade9143b1a6d23e9f132

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.6
    - setuptools
  run:
    - python =2.7|>=3.6
    - commonmark >=0.5.6
    - sphinx

test:
  imports:
    - sphinxarg

about:
  home: https://github.com/ribozz/sphinx-argparse
  license: MIT
  license_file: LICENSE
  summary: Sphinx extension that automatically documents argparse commands and options

extra:
  recipe-maintainers:
    - pmlandwehr
    - croth1
    - dpryan79
