{% set name = "sphinx-argparse" %}
{% set version = "0.5.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e5352f8fa894b6fb6fda0498ba28a9f8d435971ef4bbc1a6c9c6414e7644f032

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core
    - setuptools

  run:
    - python >=3.7
    - commonmark >=0.5.6
    - sphinx >=4.0

test:
  imports:
    - sphinxarg

about:
  home: https://github.com/ashb/sphinx-argparse
  license: MIT
  license_file: LICENSE
  summary: Sphinx extension that automatically documents argparse commands and options

extra:
  recipe-maintainers:
    - croth1
    - dpryan79
