schema_version: 1

context:
  version: "0.6.1"

package:
  name: sphinx-argparse
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-argparse/sphinx_argparse-${{ version }}.tar.gz
  sha256: f8be167aedf5670bd7c812ef515968ff4717c63cfc9cb4df5f34b54fd5649c37

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.10,<4
    - pip
  run:
    - python >=${{ python_min }}
    - sphinx >=5.1.0
    - docutils >=0.19

tests:
  - python:
      imports:
        - sphinxarg
        - sphinxarg.ext
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A sphinx extension that automatically documents argparse commands and options
  license: MIT
  license_file: LICENSE.rst
  homepage: https://sphinx-argparse.readthedocs.io/

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - croth1
    - dpryan79
